title: Marc A Hester
email: marc@hester.be
description: The personal website of Marc Aaron Hester.
url: "https://marc.hester.be"
author: Marc Hester
lang: en_US


# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
