title: Marc A Hester
email: marc@hester.be
description: My personal website.
url: "https://marc.hester.be"
author: Marc A Hester
lang: en_US
twitter:
  username: maercoftheshire
  card: summary

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
